namespace Veros.Paperless.Infra.Migrations
{
    using System.Data;
    using Veros.Data;
    using Migrator.Framework;

    [Migration(201209190141)]
    public class CriaPformal : Migration
    {
        public override void Up()
        {
            this.Database.AddTable(
                "PFORMAL",
                this.WithId("PFORMAL_CODE"),
                new Column("TYPEDOC_ID", DbType.Int32),
                new Column("PFORMAL_FORM1", DbType.AnsiString, 1),
                new Column("PFORMAL_PORTF1", DbType.Int32),
                new Column("PFORMAL_TRATF1", DbType.AnsiString, 1),
                new Column("PFORMAL_1D_CHA", DbType.AnsiString, 1),
                new Column("PFORMAL_1D_CHAVL1", DbType.Decimal),
                new Column("PFORMAL_1D_CHAVL2", DbType.Decimal),
                new Column("PFORMAL_1D_CHO", DbType.AnsiString, 1),
                new Column("PFORMAL_1D_CHOVL1", DbType.Decimal),
                new Column("PFORMAL_1D_CHOVL2", DbType.Decimal),
                new Column("PFORMAL_1D_COB", DbType.AnsiString, 1),
                new Column("PFORMAL_1D_COBVL1", DbType.Decimal),
                new Column("PFORMAL_1D_COBVL2", DbType.Decimal),
                new Column("PFORMAL_1P_CHA", DbType.AnsiString, 1),
                new Column("PFORMAL_1P_CHAVL1", DbType.Decimal),
                new Column("PFORMAL_1P_CHAVL2", DbType.Decimal),
                new Column("PFORMAL_1P_CHO", DbType.AnsiString, 1),
                new Column("PFORMAL_1P_CHOVL1", DbType.Decimal),
                new Column("PFORMAL_1P_CHOVL2", DbType.Decimal),
                new Column("PFORMAL_1P_COB", DbType.AnsiString, 1),
                new Column("PFORMAL_1P_COBVL1", DbType.Decimal),
                new Column("PFORMAL_1P_COBVL2", DbType.Decimal),
                new Column("PFORMAL_FORM2", DbType.AnsiString, 1),
                new Column("PFORMAL_PORTF2", DbType.Int32),
                new Column("PFORMAL_TRATF2", DbType.AnsiString, 1),
                new Column("PFORMAL_2D_CHA", DbType.AnsiString, 1),
                new Column("PFORMAL_2D_CHAVL1", DbType.Decimal),
                new Column("PFORMAL_2D_CHAVL2", DbType.Decimal),
                new Column("PFORMAL_2D_CHO", DbType.AnsiString, 1),
                new Column("PFORMAL_2D_CHOVL1", DbType.Decimal),
                new Column("PFORMAL_2D_CHOVL2", DbType.Decimal),
                new Column("PFORMAL_2D_COB", DbType.AnsiString, 1),
                new Column("PFORMAL_2D_COBVL1", DbType.Decimal),
                new Column("PFORMAL_2D_COBVL2", DbType.Decimal),
                new Column("PFORMAL_2P_CHA", DbType.AnsiString, 1),
                new Column("PFORMAL_2P_CHAVL1", DbType.Decimal),
                new Column("PFORMAL_2P_CHAVL2", DbType.Decimal),
                new Column("PFORMAL_2P_CHO", DbType.AnsiString, 1),
                new Column("PFORMAL_2P_CHOVL1", DbType.Decimal),
                new Column("PFORMAL_2P_CHOVL2", DbType.Decimal),
                new Column("PFORMAL_2P_COB", DbType.AnsiString, 1),
                new Column("PFORMAL_2P_COBVL1", DbType.Decimal),
                new Column("PFORMAL_2P_COBVL2", DbType.Decimal),
                new Column("PFORMAL_FORM3", DbType.AnsiString, 1),
                new Column("PFORMAL_PORTF3", DbType.Int32),
                new Column("PFORMAL_TRATF3", DbType.AnsiString, 1),
                new Column("PFORMAL_3D_CHA", DbType.AnsiString, 1),
                new Column("PFORMAL_3D_CHAVL1", DbType.Decimal),
                new Column("PFORMAL_3D_CHAVL2", DbType.Decimal),
                new Column("PFORMAL_3D_CHO", DbType.AnsiString, 1),
                new Column("PFORMAL_3D_CHOVL1", DbType.Decimal),
                new Column("PFORMAL_3D_CHOVL2", DbType.Decimal),
                new Column("PFORMAL_3D_COB", DbType.AnsiString, 1),
                new Column("PFORMAL_3D_COBVL1", DbType.Decimal),
                new Column("PFORMAL_3D_COBVL2", DbType.Decimal),
                new Column("PFORMAL_3P_CHA", DbType.AnsiString, 1),
                new Column("PFORMAL_3P_CHAVL1", DbType.Decimal),
                new Column("PFORMAL_3P_CHAVL2", DbType.Decimal),
                new Column("PFORMAL_3P_CHO", DbType.AnsiString, 1),
                new Column("PFORMAL_3P_CHOVL1", DbType.Decimal),
                new Column("PFORMAL_3P_CHOVL2", DbType.Decimal),
                new Column("PFORMAL_3P_COB", DbType.AnsiString, 1),
                new Column("PFORMAL_3P_COBVL1", DbType.Decimal),
                new Column("PFORMAL_3P_COBVL2", DbType.Decimal),
                new Column("PFORMAL_FORM4", DbType.AnsiString, 1),
                new Column("PFORMAL_PORTF4", DbType.Int32),
                new Column("PFORMAL_TRATF4", DbType.AnsiString, 1),
                new Column("PFORMAL_4D_CHA", DbType.AnsiString, 1),
                new Column("PFORMAL_4D_CHAVL1", DbType.Decimal),
                new Column("PFORMAL_4D_CHAVL2", DbType.Decimal),
                new Column("PFORMAL_4D_CHO", DbType.AnsiString, 1),
                new Column("PFORMAL_4D_CHOVL1", DbType.Decimal),
                new Column("PFORMAL_4D_CHOVL2", DbType.Decimal),
                new Column("PFORMAL_4D_COB", DbType.AnsiString, 1),
                new Column("PFORMAL_4D_COBVL1", DbType.Decimal),
                new Column("PFORMAL_4D_COBVL2", DbType.Decimal),
                new Column("PFORMAL_4P_CHA", DbType.AnsiString, 1),
                new Column("PFORMAL_4P_CHAVL1", DbType.Decimal),
                new Column("PFORMAL_4P_CHAVL2", DbType.Decimal),
                new Column("PFORMAL_4P_CHO", DbType.AnsiString, 1),
                new Column("PFORMAL_4P_CHOVL1", DbType.Decimal),
                new Column("PFORMAL_4P_CHOVL2", DbType.Decimal),
                new Column("PFORMAL_4P_COB", DbType.AnsiString, 1),
                new Column("PFORMAL_4P_COBVL1", DbType.Decimal),
                new Column("PFORMAL_4P_COBVL2", DbType.Decimal),
                new Column("PFORMAL_FORM5", DbType.AnsiString, 1),
                new Column("PFORMAL_PORTF5", DbType.Int32),
                new Column("PFORMAL_TRATF5", DbType.AnsiString, 1),
                new Column("PFORMAL_5D_CHA", DbType.AnsiString, 1),
                new Column("PFORMAL_5D_CHAVL1", DbType.Decimal),
                new Column("PFORMAL_5D_CHAVL2", DbType.Decimal),
                new Column("PFORMAL_5D_CHO", DbType.AnsiString, 1),
                new Column("PFORMAL_5D_CHOVL1", DbType.Decimal),
                new Column("PFORMAL_5D_CHOVL2", DbType.Decimal),
                new Column("PFORMAL_5D_COB", DbType.AnsiString, 1),
                new Column("PFORMAL_5D_COBVL1", DbType.Decimal),
                new Column("PFORMAL_5D_COBVL2", DbType.Decimal),
                new Column("PFORMAL_5P_CHA", DbType.AnsiString, 1),
                new Column("PFORMAL_5P_CHAVL1", DbType.Decimal),
                new Column("PFORMAL_5P_CHAVL2", DbType.Decimal),
                new Column("PFORMAL_5P_CHO", DbType.AnsiString, 1),
                new Column("PFORMAL_5P_CHOVL1", DbType.Decimal),
                new Column("PFORMAL_5P_CHOVL2", DbType.Decimal),
                new Column("PFORMAL_5P_COB", DbType.AnsiString, 1),
                new Column("PFORMAL_5P_COBVL1", DbType.Decimal),
                new Column("PFORMAL_5P_COBVL2", DbType.Decimal),
                new Column("PFORMAL_FORM6", DbType.AnsiString, 1));

            this.Database.CreateSequence("SEQ_PFORMAL");
        }

        public override void Down()
        {
            this.Database.RemoveTable("PFORMAL");
            this.Database.RemoveSequence("SEQ_PFORMAL");
        }
    }
}
