using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("9999.9.9.9")]
[assembly: AssemblyFileVersionAttribute("9999.9.9.9")]
[assembly: AssemblyCopyrightAttribute("Copyright M2Sys Tecnologia e Serviços 2012")]
[assembly: AssemblyProductAttribute("Veros Framework")]
[assembly: AssemblyCompanyAttribute("M2Sys Tecnologia e Serviços")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("9999.9.9.9")]

